---
- name: pulling images
  hosts: localhost
  gather_facts: false
  vars_files:
    - /root/ansible/2image.yml

  tasks:
    - name: docker pull command
      loop: "{{img_info}}"
      shell: "docker tag {{item.id}} AQ2NML-P-OS-REG:5007/{{item.name}}"
      ignore_errors: true

